name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install

    - name: Create environment variables file
      shell: bash
      run: |
        cat << EOF > .env
        NODE_ENV="production"
        EOF
